"""add all tables

Revision ID: 52949402356c
Revises: dc42c5a64ef7
Create Date: 2026-04-20 14:36:22.008038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.models.base import UUIDType


# revision identifiers, used by Alembic.
revision: str = '52949402356c'
down_revision: Union[str, Sequence[str], None] = 'dc42c5a64ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_work_start', sa.Time(), nullable=False),
    sa.Column('default_work_end', sa.Time(), nullable=False),
    sa.Column('break_duration_min', sa.Integer(), nullable=False),
    sa.Column('break_interval_min', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_sessions',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_start', sa.Time(), nullable=False),
    sa.Column('work_end', sa.Time(), nullable=False),
    sa.Column('config_snapshot', sa.String(length=2048), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_logs',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('task_id', UUIDType(length=36), nullable=False),
    sa.Column('work_session_id', UUIDType(length=36), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_blocks',
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('task_id', UUIDType(length=36), nullable=False),
    sa.Column('work_session_id', UUIDType(length=36), nullable=False),
    sa.Column('planned_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('planned_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_session_id'], ['work_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_blocks')
    op.drop_table('execution_logs')
    op.drop_table('work_sessions')
    op.drop_table('user_config')
    op.drop_table('tasks')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
